### ISSUE TITLE
Atom 1.17 breaks import

### ISSUE THREAD

**Issue by GuskiS** [kevinsawicki/monokai#92]
Hello. I have been using monokai theme for a while now, and recently I added my custom LESS code for TypeScript language files. For example:
```less
@import 'syntax-variables';
.syntax--ts {
  .syntax--entity.syntax--name.syntax--type,
  .syntax--meta.syntax--definition.syntax--function.entity.syntax--name.syntax--function,
  .syntax--support.syntax--function,
  .syntax--meta.syntax--definition.syntax--method.entity.syntax--name.syntax--function {
    color: @green;
  }
  //...
}
```
But after updating atom to 1.17 versiion I'm getting this error: `variable @green is undefined`

Any ideas?
